name: Generate Documentation
on:
  push:
    branches:
      - main

jobs:
  documentation:
    name: Generate and Publish Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Build documentation
        run: yarn typedoc
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
            branch: gh-pages
            folder: docs